"
# Falcon4Seaside

I am a utility class with a number of convenience methods for managing a Falcon4Seaside installation.

See the class methods for more information.

You would never create an instance of this class.
"
Class {
	#name : #Falcon4Seaside,
	#superclass : #Object,
	#category : #'Falcon4Seaside-Core'
}

{ #category : #accessing }
Falcon4Seaside class >> version [
	"The version of Falcon implemented"
	^ '3.20.0'
]
